pipeline {
    agent any

    tools {
        maven 'Maven'
        jdk 'JDK'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t your-image-name:${BUILD_NUMBER} .'
            }
        }

        stage('Docker Push') {
            steps {
                // Add commands to push to your Docker registry
            }
        }

        stage('Deploy') {
            steps {
                // Add commands to deploy your application
            }
        }
    }
}